# Generated by Django 2.2.10 on 2020-02-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200208_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
