# Generated by Django 2.2.10 on 2020-02-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
